// Victor Dos Santos Araujo, 2475553

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ghxstyzim
 */
public class FormEstagiario extends javax.swing.JFrame {

    private static FormEstagiario EstagioUnic;
    private BDFuncionario comandos = BDFuncionario.getInstanciaComandoHome();
   
    // Metodo Singleton 
    
    public static FormEstagiario geraEstagio() {
        
        if (EstagioUnic == null) {
            EstagioUnic = new FormEstagiario();
        }
        return EstagioUnic;
    }
    
            
    public FormEstagiario() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_Instituição = new javax.swing.JTextField();
        text_Curso = new javax.swing.JTextField();
        text_CargaHoraria = new javax.swing.JTextField();
        text_BolsaAuxilio = new javax.swing.JTextField();
        BtVoltar = new javax.swing.JButton();
        Text_SubtTitlle = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        Text_SubTitlle = new javax.swing.JLabel();
        textIdade = new javax.swing.JTextField();
        Text_SubtTitlle1 = new javax.swing.JLabel();
        textCPF = new javax.swing.JTextField();
        Text_SubTitlle2 = new javax.swing.JLabel();
        textSalario = new javax.swing.JTextField();
        BtCadastrar = new javax.swing.JButton();
        BtTabEstagiarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite a Instituição de Ensino:");

        jLabel2.setText("Digite o Curso: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Preencha os Campos Abaixo:");

        jLabel4.setText("Digite a Carga Horária do Estágio:");

        jLabel5.setText("Digite o Valor da bolsa auxílio:");

        text_Instituição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_InstituiçãoActionPerformed(evt);
            }
        });

        text_CargaHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_CargaHorariaActionPerformed(evt);
            }
        });

        text_BolsaAuxilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_BolsaAuxilioActionPerformed(evt);
            }
        });

        BtVoltar.setText("Voltar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        Text_SubtTitlle.setText("Nome:");

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        Text_SubTitlle.setText("CPF:");

        textIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdadeActionPerformed(evt);
            }
        });

        Text_SubtTitlle1.setText("Idade:");

        textCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCPFActionPerformed(evt);
            }
        });

        Text_SubTitlle2.setText("Salário:");

        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });

        BtTabEstagiarios.setText("Tabela Estagiarios");
        BtTabEstagiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTabEstagiariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Text_SubTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Text_SubtTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Text_SubtTitlle1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Text_SubTitlle2)
                        .addComponent(textNome)
                        .addComponent(textIdade)
                        .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCadastrar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Instituição, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_CargaHoraria)
                    .addComponent(text_Curso)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_BolsaAuxilio, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtTabEstagiarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BtVoltar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubtTitlle)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Instituição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubTitlle)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubtTitlle1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_CargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubTitlle2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_BolsaAuxilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtVoltar)
                    .addComponent(BtTabEstagiarios))
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
       voltarHome();
    }//GEN-LAST:event_BtVoltarActionPerformed

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdadeActionPerformed

    private void textCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCPFActionPerformed

    private void text_BolsaAuxilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_BolsaAuxilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_BolsaAuxilioActionPerformed

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
       try {
            registrarEstagiario();
            int ret = JOptionPane.showConfirmDialog(
                null,
                "Funcionário Registrado! Deseja cadastrar mais?",
                "Cadastro bem sucedido",
                JOptionPane.YES_NO_OPTION
            );
            if(ret == 0){
                limpar();
            } else {
                limpar();
                dispose();
            }
       } catch (CpfInvalidoException | IdadeInvalidoException | SalarioInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
       }  
    }//GEN-LAST:event_BtCadastrarActionPerformed

    private void text_CargaHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_CargaHorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_CargaHorariaActionPerformed

    private void text_InstituiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_InstituiçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_InstituiçãoActionPerformed

    private void BtTabEstagiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTabEstagiariosActionPerformed
        abreTabFunc();
    }//GEN-LAST:event_BtTabEstagiariosActionPerformed
    
     public void limpar(){
        textNome.setText("");
        textCPF.setText("");
        textSalario.setText("");
        text_BolsaAuxilio.setText("");
        text_CargaHoraria.setText("");
        text_Curso.setText("");
        text_Instituição.setText("");
        textIdade.setText("");
    }
    
    public void abreTabFunc(){
        FormTabEstag.geraTabEsg().setVisible(true);
    } 
     
     
     
     public void registrarEstagiario() throws CpfInvalidoException, IdadeInvalidoException, SalarioInvalidoException {
        Estagiario estagiario = new Estagiario();
        
        
        estagiario.setNome(textNome.getText());
        String cpfStr = textCPF.getText().trim();
        
        try {
            int cpf = Integer.parseInt(cpfStr);
            if (cpf < 0) {
                throw new CpfInvalidoException("CPF não pode ser negativo");
            }
            estagiario.setCpf(cpf);
        } catch (NumberFormatException e) {
            throw new CpfInvalidoException("CPF deve ser um número válido.");
        }
        
        int idade = Integer.parseInt(textIdade.getText().trim());
        if (idade <= 0) {
            throw new IdadeInvalidoException("Idade inválida");
        }
        estagiario.setIdade(idade);
        
        int salario = Integer.parseInt(textSalario.getText().trim());
        if (salario <= 0) {
            throw new SalarioInvalidoException("Salário Inválido");
        }
        estagiario.setSalario(salario);
        
        String instituicaoEnsino = text_Instituição.getText();
        estagiario.setInstituicaoEnsino(instituicaoEnsino);

        String curso = text_Curso.getText();
        estagiario.setCurso(curso);
        
        int chs = Integer.parseInt(text_CargaHoraria.getText().trim());
        estagiario.setCHS(chs);
        
        double bolsaAuxilio = Double.parseDouble(text_BolsaAuxilio.getText().trim());
        estagiario.setBolsaAuxilio(bolsaAuxilio);
        
        
    
        boolean registroRealizado = comandos.registrarFuncionario(estagiario);
        if (!registroRealizado) {
            
            return;
        }
        
        JOptionPane.showMessageDialog(
            null,
            "Funcionário registrado com sucesso!",
            "Cadastro de Funcionário",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    
     public void voltarHome(){
        int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente voltar ao menu principal?",
                "Saida",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ret == 0){
            dispose();
        }
    }
     
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtTabEstagiarios;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JLabel Text_SubTitlle;
    private javax.swing.JLabel Text_SubTitlle2;
    private javax.swing.JLabel Text_SubtTitlle;
    private javax.swing.JLabel Text_SubtTitlle1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textIdade;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSalario;
    private javax.swing.JTextField text_BolsaAuxilio;
    private javax.swing.JTextField text_CargaHoraria;
    private javax.swing.JTextField text_Curso;
    private javax.swing.JTextField text_Instituição;
    // End of variables declaration//GEN-END:variables
}
