// Victor Dos Santos Araujo, 2475553

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ghxstyzim
 */
public class FormFuncPj extends javax.swing.JFrame {
    
    
    private static FormFuncPj UnicPj;
    // Metodo Singleton
    private BDFuncionario comandos = BDFuncionario.getInstanciaComandoHome();
    public static FormFuncPj geraPj(){
        
        if (UnicPj == null) {
            UnicPj = new FormFuncPj();
        }
        return UnicPj;
    }
    
    public FormFuncPj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Titlle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Text_SubtTitlle = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        Text_SubTitlle = new javax.swing.JLabel();
        textIdade = new javax.swing.JTextField();
        Text_SubtTitlle1 = new javax.swing.JLabel();
        textCPF = new javax.swing.JTextField();
        Text_SubTitlle2 = new javax.swing.JLabel();
        textSalario = new javax.swing.JTextField();
        textCNPJ = new javax.swing.JTextField();
        textValorContrato = new javax.swing.JTextField();
        textDuraContrato = new javax.swing.JTextField();
        BtSair = new javax.swing.JButton();
        BtCadastrar1 = new javax.swing.JButton();
        BtTabPj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text_Titlle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Text_Titlle.setText("Preencha os Campos Abaixo:");

        jLabel1.setText("Digite o CNPJ:");

        jLabel2.setText("Digite o valor do contrato:");

        jLabel3.setText("Digite a duração do contrato (em meses):");

        Text_SubtTitlle.setText("Nome:");

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        Text_SubTitlle.setText("CPF:");

        textIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdadeActionPerformed(evt);
            }
        });

        Text_SubtTitlle1.setText("Idade:");

        textCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCPFActionPerformed(evt);
            }
        });

        Text_SubTitlle2.setText("Salário:");

        BtSair.setText("Voltar");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        BtCadastrar1.setText("Cadastrar");
        BtCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrar1ActionPerformed(evt);
            }
        });

        BtTabPj.setText("Tabela PJ");
        BtTabPj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTabPjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text_Titlle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Text_SubtTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(85, 85, 85))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_SubTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_SubtTitlle1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_SubTitlle2)
                            .addComponent(textIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(textCPF)
                            .addComponent(textNome)
                            .addComponent(textSalario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textDuraContrato)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textValorContrato)
                                    .addComponent(textCNPJ))
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtCadastrar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtTabPj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtSair)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Text_Titlle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubtTitlle)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubTitlle)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValorContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubtTitlle1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDuraContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(Text_SubTitlle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtSair)
                    .addComponent(BtCadastrar1)
                    .addComponent(BtTabPj))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdadeActionPerformed

    private void textCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCPFActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
       voltarHome();
    }//GEN-LAST:event_BtSairActionPerformed

    private void BtCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrar1ActionPerformed
       try {
        registrarPj();
        int ret = JOptionPane.showConfirmDialog(
        null,
        "Funcionario PJ Registrado! Deseja cadastrar mais?",
        "Cadastro bem sucedido",
        JOptionPane.YES_NO_OPTION
    );
    if(ret == 0){
        limpar();
    } else {
            limpar();
            dispose();
    }
    } catch (CpfInvalidoException | IdadeInvalidoException | SalarioInvalidoException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
    }  
    }//GEN-LAST:event_BtCadastrar1ActionPerformed

    private void BtTabPjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTabPjActionPerformed
       abrirTabPj();
    }//GEN-LAST:event_BtTabPjActionPerformed
     
    public void limpar(){
        textNome.setText("");
        textCPF.setText("");
        textSalario.setText("");
        textDuraContrato.setText("");
        textValorContrato.setText("");
        textCNPJ.setText("");
        textIdade.setText("");
    }
    
    
    public void registrarPj() throws CpfInvalidoException, IdadeInvalidoException, SalarioInvalidoException {
    FuncionarioPJ funcPj = new FuncionarioPJ();
    
    funcPj.setNome(textNome.getText());
    
    String cpfStr = textCPF.getText();
    int cpf = Integer.parseInt(cpfStr);
    if (cpf < 0) {
        throw new CpfInvalidoException("CPF não pode ser negativo");
    }
    funcPj.setCpf(cpf);
    
    int idade = Integer.parseInt(textIdade.getText());
    if (idade <= 0) {
        throw new IdadeInvalidoException("Idade inválida");
    }
    funcPj.setIdade(idade);
    
    int salario = Integer.parseInt(textSalario.getText());
    if (salario < 0) {
        throw new SalarioInvalidoException("Salário inválido");
    }
    funcPj.setSalario(salario);
    
    
    int valorContrato = Integer.parseInt(textValorContrato.getText());
    funcPj.setValorContrato(valorContrato);
    
   
    int tempoContrato = Integer.parseInt(textDuraContrato.getText());
    funcPj.setTempoContrato(tempoContrato);
    
    
    String cnpj = textCNPJ.getText();
    funcPj.setCnpj(cnpj);
    
    
    comandos.registrarFuncionario(funcPj);
    
    JOptionPane.showMessageDialog(null, "Funcionário registrado com sucesso!", 
                                  "Cadastro de Funcionário", JOptionPane.INFORMATION_MESSAGE);
}

    
    public void abrirTabPj(){
         FormTabFuncPj.geraTabPJ().setVisible(true);
    }
    
     public void voltarHome(){
        int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente voltar ao menu principal?",
                "Saida",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ret == 0){
            dispose();
        }
    }
     
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar1;
    private javax.swing.JButton BtSair;
    private javax.swing.JButton BtTabPj;
    private javax.swing.JLabel Text_SubTitlle;
    private javax.swing.JLabel Text_SubTitlle2;
    private javax.swing.JLabel Text_SubtTitlle;
    private javax.swing.JLabel Text_SubtTitlle1;
    private javax.swing.JLabel Text_Titlle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textCNPJ;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textDuraContrato;
    private javax.swing.JTextField textIdade;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSalario;
    private javax.swing.JTextField textValorContrato;
    // End of variables declaration//GEN-END:variables
}
