// Victor Dos Santos Araujo, 2475553

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ghxstyzim
 */
public class FormFuncTemp extends javax.swing.JFrame {
    
    
    //Metodo Singleton
    private static FormFuncTemp UnicTemporario;
    private BDFuncionario comandos = BDFuncionario.getInstanciaComandoHome();    
    public static FormFuncTemp geraTemporario(){
    
        if (UnicTemporario == null) {
        
            UnicTemporario = new FormFuncTemp();
        }
        return UnicTemporario;
    }
    
    public FormFuncTemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Titlle = new javax.swing.JLabel();
        Text_SubtTitlle = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        Text_SubTitlle = new javax.swing.JLabel();
        textIdade = new javax.swing.JTextField();
        Text_SubtTitlle1 = new javax.swing.JLabel();
        textCPF = new javax.swing.JTextField();
        Text_SubTitlle2 = new javax.swing.JLabel();
        textSalario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textValorHoras = new javax.swing.JTextField();
        textHorasTrabalhadas = new javax.swing.JTextField();
        BtSair = new javax.swing.JButton();
        BtCadastrar = new javax.swing.JButton();
        BtTabTemporarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Text_Titlle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Text_Titlle.setText("Preencha os Campos Abaixo:");

        Text_SubtTitlle.setText("Nome:");

        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        Text_SubTitlle.setText("CPF:");

        textIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdadeActionPerformed(evt);
            }
        });

        Text_SubtTitlle1.setText("Idade:");

        textCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCPFActionPerformed(evt);
            }
        });

        Text_SubTitlle2.setText("Salário:");

        jLabel2.setText("Valor das horas trabalhadas:");

        jLabel3.setText("Horas trabalhadas:");

        BtSair.setText("Voltar");
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });

        BtTabTemporarios.setText("Tabela Temporarios");
        BtTabTemporarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTabTemporariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text_Titlle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_SubTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_SubtTitlle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_SubtTitlle1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_SubTitlle2)
                            .addComponent(textNome)
                            .addComponent(textCPF)
                            .addComponent(textIdade)
                            .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(textHorasTrabalhadas)
                                .addComponent(textValorHoras))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtSair))
                            .addComponent(BtTabTemporarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text_Titlle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubtTitlle)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValorHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_SubTitlle)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHorasTrabalhadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(Text_SubtTitlle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Text_SubTitlle2)
                    .addComponent(BtTabTemporarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtSair)
                    .addComponent(BtCadastrar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
      
    }//GEN-LAST:event_textNomeActionPerformed

    private void textIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdadeActionPerformed
       
    }//GEN-LAST:event_textIdadeActionPerformed

    private void textCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCPFActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
       voltarHome();
    }//GEN-LAST:event_BtSairActionPerformed

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
        try {
        registrarTemp();
        int ret = JOptionPane.showConfirmDialog(
        null,
        "Funcionario Temporario Registrado! Deseja cadastrar mais?",
        "Cadastro bem sucedido",
        JOptionPane.YES_NO_OPTION
    );
    if(ret == 0){
        limpar();
    } else {
            limpar();
            dispose();
    }
    } catch (CpfInvalidoException | IdadeInvalidoException | NumberFormatException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Cadastro", JOptionPane.ERROR_MESSAGE);
    }   catch (SalarioInvalidoException ex) {
            Logger.getLogger(FormFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtCadastrarActionPerformed

    private void BtTabTemporariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTabTemporariosActionPerformed
      abreTabTemp();
    }//GEN-LAST:event_BtTabTemporariosActionPerformed
    
     public void limpar(){
        textNome.setText("");
        textCPF.setText("");
        textSalario.setText("");
        textHorasTrabalhadas.setText("");
        textValorHoras.setText("");
        textIdade.setText("");
    }
   
    public void abreTabTemp(){
        FormTabFuncTemp.geraTabTemp().setVisible(true);
    } 
     
     
    public void registrarTemp() throws CpfInvalidoException, IdadeInvalidoException, SalarioInvalidoException {

    FuncionarioTemporario funcTemp = new FuncionarioTemporario();
    
    funcTemp.setNome(textNome.getText());  
    String cpfStr = textCPF.getText().trim();
    
    int cpf;
    
    try {
        cpf = Integer.parseInt(cpfStr); 
    } catch (NumberFormatException e) { // Ver se tem excessao para o Cpf
        throw new CpfInvalidoException("CPF deve ser um número válido.");
    }
    if (cpf < 0) {
        throw new CpfInvalidoException("CPF não pode ser negativo");
    }
    funcTemp.setCpf(cpf);

    
    int idade;
    try {
        idade = Integer.parseInt(textIdade.getText().trim());
    } catch (NumberFormatException e) { //Ver se tem Excessao Para idade
        throw new IdadeInvalidoException("Idade deve ser um número válido.");
    }
    if (idade <= 0) {
        throw new IdadeInvalidoException("Idade inválida. Deve ser maior que 0.");
    }
    funcTemp.setIdade(idade);

    
    double salario;
    try {
        salario = Double.parseDouble(textSalario.getText().trim());
    } catch (NumberFormatException e) { // Ver se tem Excessao Para idade
        throw new SalarioInvalidoException("Salário deve ser um número válido.");
    }
    if (salario < 0) {
        throw new SalarioInvalidoException("Salário inválido. Não pode ser negativo.");
    }
    funcTemp.setSalario(salario);
    
    int vh = Integer.parseInt(textValorHoras.getText());
    funcTemp.setValorHora(vh);
    
    int ht = Integer.parseInt(textValorHoras.getText());
    funcTemp.sethorasTrabalhadas(ht);
    
    
    comandos.registrarFuncionario(funcTemp); // Registra o Funcionario
    
    JOptionPane.showMessageDialog(null, "Funcionário registrado com sucesso!", "Cadastro de Funcionário", JOptionPane.INFORMATION_MESSAGE);
}
    
     public void voltarHome(){
        int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente voltar ao menu principal?",
                "Saida",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ret == 0){
            dispose();
        }
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtSair;
    private javax.swing.JButton BtTabTemporarios;
    private javax.swing.JLabel Text_SubTitlle;
    private javax.swing.JLabel Text_SubTitlle2;
    private javax.swing.JLabel Text_SubtTitlle;
    private javax.swing.JLabel Text_SubtTitlle1;
    private javax.swing.JLabel Text_Titlle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textCPF;
    private javax.swing.JTextField textHorasTrabalhadas;
    private javax.swing.JTextField textIdade;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSalario;
    private javax.swing.JTextField textValorHoras;
    // End of variables declaration//GEN-END:variables
}
