// Victor Dos Santos Araujo, 2475553

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Ghxstyzim
 */
public class FormHome extends javax.swing.JFrame {
   
    
    private static FormHome homeUnic;
    
    // Metodo Singleton
    
    public static FormHome geraHome(){
        if(homeUnic == null){
            homeUnic = new FormHome();
        }
        return homeUnic;
    }
    /**
     * Creates new form JFormHome
     */
    
    public FormHome() {
        initComponents();
        setSize(400, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_Tittle = new javax.swing.JLabel();
        BtAddFunc = new javax.swing.JButton();
        BtAddEstag = new javax.swing.JButton();
        BtAddFuncPj = new javax.swing.JButton();
        BtAddFuncTemp = new javax.swing.JButton();
        BtExibir = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();

        Text_Tittle.setText("SELECIONE UMA DAS OPÇÕES");

        BtAddFunc.setText("Adcionar Funcionario");
        BtAddFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddFuncActionPerformed(evt);
            }
        });

        BtAddEstag.setText("Adcionar Estagiário");
        BtAddEstag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddEstagActionPerformed(evt);
            }
        });

        BtAddFuncPj.setText("Adcionar Funcionario PJ");
        BtAddFuncPj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddFuncPjActionPerformed(evt);
            }
        });

        BtAddFuncTemp.setText("Adcionar Funcionario Temporario");
        BtAddFuncTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddFuncTempActionPerformed(evt);
            }
        });

        BtExibir.setText("Exibir Todos os Funcionários");
        BtExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExibirActionPerformed(evt);
            }
        });

        BtFechar.setText("Fechar");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtAddFuncTemp)
                            .addComponent(BtAddFuncPj, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtAddEstag, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtAddFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(Text_Tittle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(BtFechar)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Text_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAddFunc)
                .addGap(12, 12, 12)
                .addComponent(BtAddEstag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtAddFuncPj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAddFuncTemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtExibir)
                .addGap(24, 24, 24)
                .addComponent(BtFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    /*Parte das Funçoes dos Botoes*/
    
    
    private void BtAddFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddFuncActionPerformed
        abreFunc();
    }//GEN-LAST:event_BtAddFuncActionPerformed

    private void BtAddEstagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddEstagActionPerformed
        abreEstagio();    
    }//GEN-LAST:event_BtAddEstagActionPerformed

    private void BtAddFuncTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddFuncTempActionPerformed
       abreTemporario();
    }//GEN-LAST:event_BtAddFuncTempActionPerformed

    private void BtAddFuncPjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddFuncPjActionPerformed
        abrePj();
    }//GEN-LAST:event_BtAddFuncPjActionPerformed

    private void BtExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExibirActionPerformed
        abreTab();
    }//GEN-LAST:event_BtExibirActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        fechaHome();
    }//GEN-LAST:event_BtFecharActionPerformed

    
    public void abreFunc(){
      FormFuncionario.geraFunc().setVisible(true); 
    }
    
    public void abreEstagio(){
        FormEstagiario.geraEstagio().setVisible(true);
    }
    public void abrePj() {
        
        FormFuncPj.geraPj().setVisible(true);
    }
    
    public void abreTemporario(){
        FormFuncTemp.geraTemporario().setVisible(true);
    }
    
    public void fechaHome(){
       FormHome.geraHome().setVisible(false);
    }
    
    public void abreTab() {
        FormTabFunc.geraTabFuncionarios().setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddEstag;
    private javax.swing.JButton BtAddFunc;
    private javax.swing.JButton BtAddFuncPj;
    private javax.swing.JButton BtAddFuncTemp;
    private javax.swing.JButton BtExibir;
    private javax.swing.JButton BtFechar;
    private javax.swing.JLabel Text_Tittle;
    // End of variables declaration//GEN-END:variables
}
