// Victor dos Santos Araujo - 2475553

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ghxstyzim
 */
public class FormTabFuncPj extends javax.swing.JFrame {
    
    private BDFuncionario comandos = BDFuncionario.getInstanciaComandoHome();
     private static FormTabFuncPj geraTabUnic;
   
    // Metodo Singleton 
    public static FormTabFuncPj geraTabPJ(){
        if(geraTabUnic == null){
            geraTabUnic = new FormTabFuncPj();
        }
        return geraTabUnic;
    }
    
    
    public FormTabFuncPj() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePj = new javax.swing.JTable();
        BtAtualizar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textCPF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtVoltar.setText("Voltar");
        BtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Funcionarios PJ abaixo:");

        tablePj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Idade", "Salario", "Valor Cont.", "Tempo Cont.", "CNPJ"
            }
        ));
        jScrollPane1.setViewportView(tablePj);

        BtAtualizar.setText("Atualizar");
        BtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAtualizarActionPerformed(evt);
            }
        });

        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Qual CPF deseja retirar do sistema?");

        textCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(BtExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtAtualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtVoltar))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtAtualizar)
                        .addComponent(BtVoltar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtExcluir)
                            .addComponent(textCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVoltarActionPerformed
        voltarHome();
        limpar();
    }//GEN-LAST:event_BtVoltarActionPerformed

    private void BtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAtualizarActionPerformed
        popularTbPj();
    }//GEN-LAST:event_BtAtualizarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
       try {
            excFuncionarioPj();
            popularTbPj();
        } catch (CpfInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de CPF", JOptionPane.ERROR_MESSAGE);
        }
        limpar();
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void textCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCPFActionPerformed

    /**
     */
   
    public void limpar(){
        textCPF.setText("");
    }
    public void excFuncionarioPj() throws CpfInvalidoException {
    
    String cpfStr = textCPF.getText().trim();
    
    if(cpfStr.isEmpty()){
        JOptionPane.showMessageDialog(null, "Por favor, informe um CPF válido!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        int cpf = Integer.parseInt(cpfStr);
       
        FuncionarioPJ funcPj = new FuncionarioPJ();
        funcPj.setCpf(cpf);
        
        boolean removido = comandos.exFuncionarioCPF(funcPj);
        if (removido) {
            JOptionPane.showMessageDialog(null, "Funcionário removido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Funcionário com CPF " + cpf + " não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch(NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "CPF inválido! Certifique-se de que o CPF seja um número.", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    }

     public void popularTbPj(){

        DefaultTableModel modelo = (DefaultTableModel) tablePj.getModel();
        modelo.setRowCount(0); 

        for (FuncionarioPJ pj : comandos.getBdPj()) {
        modelo.addRow(new Object[]{ pj.getNome(), pj.getCpf(), pj.getIdade(), pj.getSalario(),pj.getValorContrato(),pj.getTempoContrato(), pj.getCnpj()});
        }
    }
     
    public void voltarHome(){
        int ret = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente voltar?",
                "Saida",
                JOptionPane.YES_NO_CANCEL_OPTION
        );
        if(ret == 0){
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAtualizar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePj;
    private javax.swing.JTextField textCPF;
    // End of variables declaration//GEN-END:variables
}
